import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/helix/helixcss.css";
import "@/styles/main.scss";

const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "@/contexts/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-10`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
